apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  configuration.yaml: |-
{{- range $key, $val := .Values.db.configuration }}
{{ $key | indent 6}}: {{ $val }}
{{- end}}
